source:
  datasource:
    url: jdbc:mysql://localhost:3306/different?useSSL=false&useUnicode=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    schema-name: different
target:
  datasource:
    url: jdbc:mysql://localhost:3306/different2?useSSL=false&useUnicode=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    schema-name: different2
